<?php
require_once __DIR__.'/config.php';
require_login();$title='Appointments';$pdo=db();$u=auth();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();
if(isset($_POST['delete_id'])){$pdo->prepare("DELETE FROM appointments WHERE id=?")->execute([(int)$_POST['delete_id']]);flash('success','Appointment deleted.');redirect('appointments.php');}
$id=(int)($_POST['id']??0);$pid=(int)$_POST['patient_id'];$did=$u['role']==='doctor'?(int)$pdo->query("SELECT id FROM doctors WHERE user_id=".(int)$u['id'])->fetchColumn():(int)$_POST['doctor_id'];$date=post('appointment_date');$time=post('appointment_time');$reason=post('reason');$status=post('status')?:'Scheduled';
if(!$pid||!$did||!$date||!$time){flash('error','Patient, doctor, date and time are required.');redirect('appointments.php');}
try{if($id){$s=$pdo->prepare("UPDATE appointments SET patient_id=?,doctor_id=?,appointment_date=?,appointment_time=?,reason=?,status=? WHERE id=?");$s->execute([$pid,$did,$date,$time,$reason,$status,$id]);flash('success','Appointment updated.');}else{$s=$pdo->prepare("INSERT INTO appointments(patient_id,doctor_id,appointment_date,appointment_time,reason) VALUES(?,?,?,?,?)");$s->execute([$pid,$did,$date,$time,$reason]);flash('success','Appointment scheduled.');}}catch(Throwable $e){flash('error','That doctor/time slot is already booked or invalid.');}redirect('appointments.php');}
$edit=null;if(!empty($_GET['edit'])){$s=$pdo->prepare("SELECT * FROM appointments WHERE id=?");$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
$patients=$u['role']==='doctor'? (function()use($pdo,$u){$d=$pdo->prepare("SELECT id FROM doctors WHERE user_id=?");$d->execute([$u['id']]);$did=$d->fetchColumn();$s=$pdo->prepare("SELECT id,full_name FROM patients WHERE doctor_id=? ORDER BY full_name");$s->execute([$did]);return $s->fetchAll();})() : $pdo->query("SELECT id,full_name FROM patients ORDER BY full_name")->fetchAll();
$doctors=$pdo->query("SELECT d.id,u.full_name FROM doctors d JOIN users u ON u.id=d.user_id ORDER BY u.full_name")->fetchAll();
$rows=$u['role']==='doctor'?(function()use($pdo,$u){$d=$pdo->prepare("SELECT id FROM doctors WHERE user_id=?");$d->execute([$u['id']]);$did=$d->fetchColumn();$s=$pdo->prepare("SELECT a.*,p.full_name patient_name,u.full_name doctor_name FROM appointments a JOIN patients p ON p.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id JOIN users u ON u.id=d.user_id WHERE a.doctor_id=? ORDER BY a.appointment_date DESC,a.appointment_time DESC");$s->execute([$did]);return $s->fetchAll();})():$pdo->query("SELECT a.*,p.full_name patient_name,u.full_name doctor_name FROM appointments a JOIN patients p ON p.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id JOIN users u ON u.id=d.user_id ORDER BY a.appointment_date DESC,a.appointment_time DESC")->fetchAll();
require 'header.php'; ?>
<h1>Appointment Management</h1><div class="panel"><h2><?=$edit?'Edit Appointment':'Schedule Appointment'?></h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><?php if($edit):?><input type="hidden" name="id" value="<?=$edit['id']?>"><?php endif;?><div class="formgrid">
<div class="field"><label>Patient</label><select name="patient_id" required><option value="">Select</option><?php foreach($patients as $p):?><option value="<?=$p['id']?>" <?=(($edit['patient_id']??'')==$p['id'])?'selected':''?>><?=e($p['full_name'])?></option><?php endforeach;?></select></div>
<?php if($u['role']==='admin'): ?><div class="field"><label>Doctor</label><select name="doctor_id" required><option value="">Select</option><?php foreach($doctors as $d):?><option value="<?=$d['id']?>" <?=(($edit['doctor_id']??'')==$d['id'])?'selected':''?>><?=e($d['full_name'])?></option><?php endforeach;?></select></div><?php endif;?>
<div class="field"><label>Date</label><input type="date" name="appointment_date" min="<?=date('Y-m-d')?>" value="<?=e($edit['appointment_date']??'')?>" required></div><div class="field"><label>Time</label><input type="time" name="appointment_time" value="<?=e($edit['appointment_time']??'')?>" required></div>
<div class="field"><label>Reason</label><input name="reason" value="<?=e($edit['reason']??'')?>"></div>
<?php if($edit):?><div class="field"><label>Status</label><select name="status"><option <?=(($edit['status']??'')==='Scheduled')?'selected':''?>>Scheduled</option><option <?=(($edit['status']??'')==='Completed')?'selected':''?>>Completed</option><option <?=(($edit['status']??'')==='Cancelled')?'selected':''?>>Cancelled</option></select></div><?php endif;?>
</div><br><button class="btn"><?=$edit?'Save Changes':'Schedule'?></button><?php if($edit):?> <a href="appointments.php" class="btn btn-danger" style="background:#64748b;">Cancel</a><?php endif;?></form></div><br>
<div class="panel"><h2>Scheduled Appointments</h2><table><tr><th>Date</th><th>Time</th><th>Patient</th><th>Doctor</th><th>Reason</th><th>Status</th><th>Actions</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['appointment_date'])?></td><td><?=e($r['appointment_time'])?></td><td><?=e($r['patient_name'])?></td><td><?=e($r['doctor_name'])?></td><td><?=e($r['reason'])?></td><td><?=e($r['status'])?></td><td><div style="display:flex;gap:0.5rem;"><a href="appointments.php?edit=<?=$r['id']?>" class="btn" style="padding:0.25rem 0.5rem;font-size:0.875rem;">Edit</a><form method="post" onsubmit="return confirm('Delete this appointment?');" style="margin:0;"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="delete_id" value="<?=$r['id']?>"><button class="btn btn-danger" style="padding:0.25rem 0.5rem;font-size:0.875rem;">Delete</button></form></div></td></tr><?php endforeach;?></table></div>
<?php require 'footer.php'; ?>
