<?php
require_once __DIR__.'/config.php';
require_login();$title='Appointments';$pdo=db();$u=auth();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$pid=(int)$_POST['patient_id'];$did=$u['role']==='doctor'?(int)$pdo->query("SELECT id FROM doctors WHERE user_id=".(int)$u['id'])->fetchColumn():(int)$_POST['doctor_id'];$date=post('appointment_date');$time=post('appointment_time');$reason=post('reason');
if(!$pid||!$did||!$date||!$time){flash('error','Patient, doctor, date and time are required.');redirect('appointments.php');}
try{$s=$pdo->prepare("INSERT INTO appointments(patient_id,doctor_id,appointment_date,appointment_time,reason) VALUES(?,?,?,?,?)");$s->execute([$pid,$did,$date,$time,$reason]);flash('success','Appointment scheduled.');}catch(Throwable $e){flash('error','That doctor/time slot is already booked or invalid.');}redirect('appointments.php');}
$patients=$u['role']==='doctor'? (function()use($pdo,$u){$d=$pdo->prepare("SELECT id FROM doctors WHERE user_id=?");$d->execute([$u['id']]);$did=$d->fetchColumn();$s=$pdo->prepare("SELECT id,full_name FROM patients WHERE doctor_id=? ORDER BY full_name");$s->execute([$did]);return $s->fetchAll();})() : $pdo->query("SELECT id,full_name FROM patients ORDER BY full_name")->fetchAll();
$doctors=$pdo->query("SELECT d.id,u.full_name FROM doctors d JOIN users u ON u.id=d.user_id ORDER BY u.full_name")->fetchAll();
$rows=$u['role']==='doctor'?(function()use($pdo,$u){$d=$pdo->prepare("SELECT id FROM doctors WHERE user_id=?");$d->execute([$u['id']]);$did=$d->fetchColumn();$s=$pdo->prepare("SELECT a.*,p.full_name patient_name,u.full_name doctor_name FROM appointments a JOIN patients p ON p.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id JOIN users u ON u.id=d.user_id WHERE a.doctor_id=? ORDER BY a.appointment_date DESC,a.appointment_time DESC");$s->execute([$did]);return $s->fetchAll();})():$pdo->query("SELECT a.*,p.full_name patient_name,u.full_name doctor_name FROM appointments a JOIN patients p ON p.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id JOIN users u ON u.id=d.user_id ORDER BY a.appointment_date DESC,a.appointment_time DESC")->fetchAll();
require 'header.php'; ?>
<h1>Appointment Management</h1><div class="panel"><h2>Schedule Appointment</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><div class="formgrid">
<div class="field"><label>Patient</label><select name="patient_id" required><option value="">Select</option><?php foreach($patients as $p):?><option value="<?=$p['id']?>"><?=e($p['full_name'])?></option><?php endforeach;?></select></div>
<?php if($u['role']==='admin'): ?><div class="field"><label>Doctor</label><select name="doctor_id" required><option value="">Select</option><?php foreach($doctors as $d):?><option value="<?=$d['id']?>"><?=e($d['full_name'])?></option><?php endforeach;?></select></div><?php endif;?>
<div class="field"><label>Date</label><input type="date" name="appointment_date" min="<?=date('Y-m-d')?>" required></div><div class="field"><label>Time</label><input type="time" name="appointment_time" required></div>
<div class="field full"><label>Reason</label><input name="reason"></div></div><br><button class="btn">Schedule</button></form></div><br>
<div class="panel"><h2>Scheduled Appointments</h2><table><tr><th>Date</th><th>Time</th><th>Patient</th><th>Doctor</th><th>Reason</th><th>Status</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['appointment_date'])?></td><td><?=e($r['appointment_time'])?></td><td><?=e($r['patient_name'])?></td><td><?=e($r['doctor_name'])?></td><td><?=e($r['reason'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></table></div>
<?php require 'footer.php'; ?>
