<?php
require_once __DIR__.'/config.php';
require_login(); $title='Patient Management';$pdo=db();$u=auth();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$id=(int)($_POST['id']??0);$name=post('full_name');$gender=post('gender');$dob=post('date_of_birth')?:null;$phone=post('phone');$address=post('address');$ec=post('emergency_contact');$ep=post('emergency_phone');$_rawDid=(int)($_POST['doctor_id']??0);$doctorId=$u['role']==='doctor'?(int)$pdo->query("SELECT id FROM doctors WHERE user_id=".(int)$u['id'])->fetchColumn():($_rawDid?:null);
if(!$name||!$phone){flash('error','Full name and phone are required.');redirect('patients.php');}
if($id){$s=$pdo->prepare("UPDATE patients SET full_name=?,gender=?,date_of_birth=?,phone=?,address=?,emergency_contact=?,emergency_phone=?,doctor_id=? WHERE id=?");$s->execute([$name,$gender,$dob,$phone,$address,$ec,$ep,$doctorId,$id]);flash('success','Patient updated.');}else{$s=$pdo->prepare("INSERT INTO patients(doctor_id,full_name,gender,date_of_birth,phone,address,emergency_contact,emergency_phone) VALUES(?,?,?,?,?,?,?,?)");$s->execute([$doctorId,$name,$gender,$dob,$phone,$address,$ec,$ep]);flash('success','Patient registered.');}redirect('patients.php');}
$doctors=$pdo->query("SELECT d.id,u.full_name FROM doctors d JOIN users u ON u.id=d.user_id ORDER BY u.full_name")->fetchAll();
if($u['role']==='doctor'){$did=(int)$pdo->query("SELECT id FROM doctors WHERE user_id=".(int)$u['id'])->fetchColumn();$s=$pdo->prepare("SELECT p.*,u.full_name doctor_name FROM patients p LEFT JOIN doctors d ON d.id=p.doctor_id LEFT JOIN users u ON u.id=d.user_id WHERE p.doctor_id=? ORDER BY p.id DESC");$s->execute([$did]);$rows=$s->fetchAll();}else{$rows=$pdo->query("SELECT p.*,u.full_name doctor_name FROM patients p LEFT JOIN doctors d ON d.id=p.doctor_id LEFT JOIN users u ON u.id=d.user_id ORDER BY p.id DESC")->fetchAll();}
require 'header.php'; ?>
<h1>Patient Management</h1><div class="panel"><h2>Register New Patient</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><div class="formgrid">
<div class="field"><label>Full name</label><input name="full_name" required></div><div class="field"><label>Gender</label><select name="gender"><option>Male</option><option>Female</option><option>Other</option></select></div>
<div class="field"><label>Date of birth</label><input type="date" name="date_of_birth"></div><div class="field"><label>Phone</label><input name="phone" required></div>
<div class="field"><label>Address</label><input name="address"></div><div class="field"><label>Emergency contact</label><input name="emergency_contact"></div><div class="field"><label>Emergency phone</label><input name="emergency_phone"></div>
<?php if($u['role']==='admin'): ?><div class="field"><label>Assigned doctor</label><select name="doctor_id"><option value="">Unassigned</option><?php foreach($doctors as $d): ?><option value="<?=$d['id']?>"><?=e($d['full_name'])?></option><?php endforeach;?></select></div><?php endif; ?>
</div><br><button class="btn">Register Patient</button></form></div><br><div class="panel"><h2>Patient List</h2><table><tr><th>ID</th><th>Name</th><th>Gender</th><th>DOB</th><th>Phone</th><th>Doctor</th></tr><?php foreach($rows as $r): ?><tr><td><?=$r['id']?></td><td><?=e($r['full_name'])?></td><td><?=e($r['gender'])?></td><td><?=e($r['date_of_birth'])?></td><td><?=e($r['phone'])?></td><td><?=e($r['doctor_name']??'Unassigned')?></td></tr><?php endforeach;?></table></div>
<?php require 'footer.php'; ?>
