<?php
require_role('doctor');$title='Medical Records';$pdo=db();$uid=(int)auth()['id'];$d=$pdo->prepare("SELECT id FROM doctors WHERE user_id=?");$d->execute([$uid]);$did=(int)$d->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$pid=(int)$_POST['patient_id'];$diagnosis=post('diagnosis');$treatment=post('treatment');$notes=post('notes');if(!$pid||!$diagnosis||!$treatment){flash('error','Patient, diagnosis and treatment are required.');redirect('records.php');}$s=$pdo->prepare("INSERT INTO medical_records(patient_id,doctor_id,diagnosis,treatment,notes) VALUES(?,?,?,?,?)");$s->execute([$pid,$did,$diagnosis,$treatment,$notes]);flash('success','Medical record saved.');redirect('records.php');}
$s=$pdo->prepare("SELECT id,full_name FROM patients WHERE doctor_id=? ORDER BY full_name");$s->execute([$did]);$patients=$s->fetchAll();
$s=$pdo->prepare("SELECT r.*,p.full_name patient_name FROM medical_records r JOIN patients p ON p.id=r.patient_id WHERE r.doctor_id=? ORDER BY r.recorded_at DESC");$s->execute([$did]);$rows=$s->fetchAll();require 'header.php';?>
<h1>Medical Record Management</h1><div class="panel"><h2>Record Diagnosis & Treatment</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><div class="formgrid">
<div class="field"><label>Patient</label><select name="patient_id" required><option value="">Select</option><?php foreach($patients as $p):?><option value="<?=$p['id']?>"><?=e($p['full_name'])?></option><?php endforeach;?></select></div>
<div class="field"><label>Diagnosis</label><input name="diagnosis" required></div><div class="field"><label>Treatment</label><textarea name="treatment" required></textarea></div><div class="field"><label>Notes</label><textarea name="notes"></textarea></div></div><br><button class="btn">Save Record</button></form></div><br>
<div class="panel"><h2>Existing Records</h2><table><tr><th>Date</th><th>Patient</th><th>Diagnosis</th><th>Treatment</th><th>Notes</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['recorded_at'])?></td><td><?=e($r['patient_name'])?></td><td><?=e($r['diagnosis'])?></td><td><?=e($r['treatment'])?></td><td><?=e($r['notes'])?></td></tr><?php endforeach;?></table></div><?php require 'footer.php';?>
